[package]
name = "sample2"
version = "0.1.0"
authors = ["masaki4423 <kashiwabara356@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"